# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x05micro\"\x1d\n\nGetRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\x0bGetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t28\n\x08MicroApi\x12,\n\x03Get\x12\x11.micro.GetRequest\x1a\x12.micro.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=23
  _globals['_GETREQUEST']._serialized_end=52
  _globals['_GETRESPONSE']._serialized_start=54
  _globals['_GETRESPONSE']._serialized_end=84
  _globals['_MICROAPI']._serialized_start=86
  _globals['_MICROAPI']._serialized_end=142
# @@protoc_insertion_point(module_scope)
